/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.math.PI

class Coche {
    var marca: String = "Ford"
    var modelo: Int = 2020
}

// 1) Interface Perimetrable
interface Perimetrable {
    fun calcularPerimetro(): Double
}

class Rectangulo(val ancho: Double, val alto: Double) : Perimetrable {
    // calculada una sola vez
    val area: Double = ancho * alto

    override fun calcularPerimetro(): Double = 2 * (ancho + alto)
    override fun toString(): String = "Rectángulo(${ancho} x ${alto})"

    init {
        println("Se ha creado un rectángulo de $ancho x $alto con un área de $area")
    }

    fun describir() {
        println("Este es un rectángulo.")
    }
}

// 3) Circulo que implementa Perimetrable
class Circulo(val radio: Double) : Perimetrable {
    override fun calcularPerimetro(): Double = 2 * PI * radio
    override fun toString(): String = "Círculo(r=$radio)"
}

fun main() {
    println("--- 1. Creando un objeto de clase coche ---")
    val miCoche = Coche()
    println("Marca: ${miCoche.marca}")
    println("Modelo: ${miCoche.modelo}")

    println("\n--- 2. Creando un objeto de clase rectangulo ---")
    val rectangulo1 = Rectangulo(10.0, 5.0)
    println("El área del rectángulo es: ${rectangulo1.area}")
    rectangulo1.describir()
    val perimetro = rectangulo1.calcularPerimetro()
    println("El perímetro del rectángulo es: $perimetro")

    val formas: List<Perimetrable> = listOf(
        Rectangulo(10.0, 5.0),
        Circulo(3.0)
    )

    formas.forEach { f ->
        println("$f → perímetro = ${"%.2f".format(f.calcularPerimetro())}")
    }
}
